### ISSUE TITLE
Safari Bug - Cannot click inside text field to enter hex colour value

### ISSUE THREAD

**Issue by richhayler** [TopShelfCraft/Hue#1]
Can’t click inside the text field to enter a hex colour value in Safari. Also if I select a colour using the colour picker it doesn’t add that hex colour code to the text field. This looks like a bug that may be only related to Safari. If I try using the field in chrome on Windows it works perfectly.

**Comment by samhcorney** [comment]
+1 ...Getting this issue as well. Running Safari on a Mac. Doesn't seem to store any of the changes at all. Works fine in chrome!

**Comment by michaelrog** [comment]
Fixed by @dubcanada in PR #3!
